point_cloud_colorizer_node:
  ros__parameters:
    topics:
      img_topic: /usb_cam/image_raw
      pc_topic: /velodyne_points
    camera:
      translation:
        t_x: 0.01
        t_y: -0.0001
        t_z: 0.05
      fov:
        vFOV: 0.558
        hFOV: 0.744
      image_bounds:
        W: 640
        H: 480