image_width: 640
image_height: 480
camera_name: webcam_logitech
camera_matrix:
  rows: 3
  cols: 3
  data: [761.01996,   0.     , 278.06178,
           0.     , 760.19045, 235.02089,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.253534, -1.356252, -0.005082, -0.021357, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [745.79596,   0.     , 263.61323,   0.     ,
           0.     , 771.7605 , 233.18958,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
